<!doctype html>
<html>
	<html lang="en">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Status Page</title>
		<meta name="robots" content="noindex, nofollow, noarchive">
		<script src="/assets/js/monitor.js"></script>
		<script src="/assets/js/mustache.js"></script>
		<style>
			* { box-sizing: border-box }
			body {
				font-family: 'Open Sans', sans-serif;
				font-size: 1rem;
				line-height: 1.62;
				margin: 0;
			}
			table {
				width: 100%;
				border-collapse: collapse;
			}
			th {
				text-align: left;
			}
			main {
				width: 80%;
				margin: 0 auto;
			}
			h1, h2, h3 {
				font-weight: 400;
			}
			.grid {
				float: left;
				padding: 0 1rem;
			}
			.grid-column-1-2 {
				width: 50%;
			}
		</style>
	</head>
	<body>
		<main>
			<div class="grid grid-column-1-2">
				<h2>CPU</h2>

				<table class="cpu">
					<thead>
						<tr>
							<th width="50%">CPU</th>
							<th>Usage</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>

				<script id="cpu-template" type="x-tmpl-mustache">
					<tr>
						<td>{{ cpu }}</td>
						<td>{{ usage }}</td>
					</tr>
				</script>

				<script>
					new Monitor('cpu', {
						container: '.cpu tbody',
						template: '#cpu-template',
					});
				</script>

				<h2>Memory</h2>

				<table class="memory">
					<tbody></tbody>
				</table>

				<script id="memory-template" type="x-tmpl-mustache">
					<tr>
						<th>Total</th>
						<td>{{ total }}</td>
					</tr>
					<tr>
						<th>Free</th>
						<td>{{ free }}</td>
					</tr>
					<tr>
						<th>Buffers</th>
						<td>{{ buffers }}</td>
					</tr>
					<tr>
						<th>Cached</th>
						<td>{{ cached }}</td>
					</tr>
				</script>

				<script>
					new Monitor('memory', {
						container: '.memory tbody',
						template: '#memory-template',
					});
				</script>

				<h2>IO</h2>

				<table class="io">
					<thead>
						<tr>
							<th width="50%">Device</th>
							<th>Usage</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>

				<script id="io-template" type="x-tmpl-mustache">
					<tr>
						<td>{{ device }}</td>
						<td>{{ usage }}</td>
					</tr>
				</script>

				<script>
					new Monitor('io', {
						container: '.io tbody',
						template: '#io-template',
					});
				</script>
			</div>
			<div class="grid grid-column-1-2">
				<h2>Processes</h2>

				<table class="ps">
					<thead>
						<tr>
							<th width="20%">Memory</th>
							<th>Command</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>

				<script id="ps-template" type="x-tmpl-mustache">
					<tr>
						<td>{{ memory }}</td>
						<td>{{ cmd }}</td>
					</tr>
				</script>

				<script>
					new Monitor('ps', {
						container: '.ps tbody',
						template: '#ps-template',
					});
				</script>
			</div>
		</main>
	</body>
</html>
